[camera1]
IS_ROTATE = true
FOR_PC = true
# whether show the img in the system
SHOW_CV_MONITOR_WINDOWS = false
# the gain of img in the system shown img
MONITOR_IMG_GAIN = [30, 30, 30]

SN = "FGV22100004"
ROI_width = 1024
ROI_height = 768
sensor_width = 1280
sensor_height = 1024
nBinning = 1
FPS = 60.0
# how many frames per second to get from camera api, 
# note that it is recommanded to set it to 100 - 200 int, 
# too many will cause the system busy, 
# and too few will cause the delay of the system
frame_refresh_rate = 100
# how many frames to average for delay calculation
avg_frame_delay_num = 300
# whether publish the msg
publish_image_msg = false
publish_camera_info_msg = false


[detector]
SHOW_CV_MONITOR_WINDOWS = true
# how many frames to average for delay calculation
SHOW_CV_CAL_DELAY = true
avg_frame_delay_num = 300
SHOW_TARGET_ANGLE = false
target_lost_threshold_ms = 300

[kalman]

[kalman.process]
sigma_a_pitch_deg_s2 = 60.0
sigma_a_yaw_deg_s2 = 80.0

[kalman.measurement]
r_pitch = 0.20
r_yaw = 0.20
chi2_gate = 9.21

[kalman.timing]
vision_latency_ms = 25.0
max_meas_age_ms = 120.0
future_slop_ms = 5.0

[kalman.robust]
jitter_var_gain_deg2_per_s2 = 8.0
